PACKAGE_NAME="medion-signium-keyboard"
PACKAGE_VERSION="1.1"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build LLVM=1 modules"
BUILT_MODULE_NAME[0]="medion_kbd"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
